kubevirt/macvtap-cni

Makefile, automation/release.sh, hack/version.sh, version/description, version/version.go
Enables the developers to generate releases via `make release`.
Adds a v0.0.0 dummy release - version/...
=> Generate a release via `make release`

Makefile, hack/generate-manifests.sh, manifests/macvtap.yaml, manifests/namespace.yaml, manifests/scc.yaml, templates/macvtap.yaml.in, templates/namespace.yaml.in, templates/scc.yaml.in
Adds required information to the templates, so it can be added to CNAO.
- image pull policy
- namespace
Also add a security context constraint, which is mandatory for OKD.
=> Unify template manifest

version/description, version/version.go
This release exposes by default all interfaces in each node within the cluster,
enabling the user to create macvtap interfaces on top of them, without explicitly
configuring the macvtap device plugin.
=> Release v0.2.0

hack/generate-manifests.sh, templates/macvtap.yaml.in
Missing quotation causes issues when the yaml is being processed with yq
Adds quotation marks around `{{  }}` to macvtap.yaml.in so that it can be processed with `yq`.
```release-note
NONE
```
=> Adding quotes in macvtap.yaml.in

version/description, version/version.go
Signed-off-by: Petr Horacek <phoracek@redhat.com>
We need to release new manifest templates.
=> Release v0.3.0

templates/macvtap.yaml.in
Use double quotes instead of single quotes in:
command: ["cp", "/macvtap-cni", "/host/opt/cni/bin/macvtap"]
**Release notes**:
```release notes
NONE
```
=> Fix container command quotes in macvtap.yaml.in

version/description, version/version.go
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
This release updates dependencies to align with kubernetes v1.19.1.
**Release notes**
```release-note
NONE
```
=> Release v0.4.0

go.mod, go.sum, hack/functest.sh, tests/e2e/macvtap_test.go, vendor/github.com/pkg/errors/.gitignore, vendor/github.com/pkg/errors/.travis.yml, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/Makefile, vendor/github.com/pkg/errors/README.md, vendor/github.com/pkg/errors/appveyor.yml, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/go113.go, vendor/github.com/pkg/errors/stack.go, vendor/modules.txt
This PR will allow running the
functest as tier1 test in other repos' deploying
macvtap pod, using their clusters.
- **tier1, Change KUBECONFIG to be configurable in functest**
Currently, functests only use the repo's KUBECONFIG
configuration. This means that tests will run only
on clusters generated by this repo.
Changed KUBECONFIG in hack/functest.sh to be
configurable.
- **tier1, Change tests to get namespace from cluster**
Currently, the test assumes that the macvtap pod
is in default namespace.
This mean that we can't perform tier1 test
if the macvtap is deployed on another namespace.
Changed to get the namespace of the macvtap
daemonset.
=> tier1 tests, Modify tests for tier1

version/description, version/version.go
This PR issues a new patch release v0.4.1.
it's sole content is to enable to run tier1 tests on external operators, such as [CNAO](https://github.com/kubevirt/cluster-network-addons-operator)
related PR in CNAO: [macvtap tier1 automation](https://github.com/kubevirt/cluster-network-addons-operator/pull/638)
```release-note
Release v0.4.1
```
=> Release v0.4.1

.gitignore, Makefile, hack/functest.sh, hack/install-go.sh
Currently, if go is not installed on the host
then e2e tests will fail.
We want to be independent of this.
Added install of vendored go, according to
the version in go.mod
=> ci, Add vendored-go to Makefile

tests/e2e/macvtap_test.go
Curretnly, we are using an old Daemonset version (extensions/v1beta1)
While this works on the repo, it will fail if run from
a repo using a newer Daemonset version (apps/v1).
The solution is to use the latest version that recognizes also
the old version.
=> ci, Fix wrong daemonset call in macvtap tests

version/description, version/version.go
This PR issues a new patch release v0.4.2
```release-note
Release v0.4.2
```
=> Release v0.4.2

README.md
The project's README currently points to examples using the `master` branch, which was recently renamed to `main`.
This PR corrects the README file.
=> readme: refer to the new default branch

README.md, examples/macvtap-deviceplugin-config-explicit.yaml, pkg/deviceplugin/lister.go, pkg/deviceplugin/plugin.go, pkg/deviceplugin/plugin_test.go, pkg/util/netlink.go
This PR renames the `master` attribute of the device plugin configuration to `lowerDevice` to foster inclusive language.
```release-note
Rename the DP configuration `master` attribute to `lowerDevice`, thus fostering inclusive language.
```
=> Rename master api

manifests/macvtap.yaml, templates/macvtap.yaml.in
As part of https://bugzilla.redhat.com/show_bug.cgi?id=1953482
We are adding Priority Class [1] to each network component.
The motivation is to make the control plane pods less sensitive to preemption
than user workloads.
Pods that are node specific will have the higher build-in priority,
since preempting them from a specific node, makes them unavailable
until they are rescheduled on that specific node.
Pods that are network control plane, but are not node specific 
will have `system-cluster-critical`, which would still make them more important 
than user and custom workloads, but less than `system-node-critical`.
Add `system-node-critical` to `macvtap-cni` DaemonSet.
Since `macvtap-cni` pod should run on each node,
assign `system-node-critical` pc to it.
[1] …
=> DaemonSet, Add Priority class

manifests/macvtap.yaml, templates/macvtap.yaml.in
Add minimum required cpu and memory resources
for the initContainer.
Based on empiric checks (set limits and see the minimum
required).
The checks were did as follows:
Set CPU and memory limits. and see which are the minimal values that allow
the initConatiner to run flawlessly.
Setting the limit for development only allows to simulate a congested cluster,
which will allow only the "requests" to be fulfilled.
See https://bugzilla.redhat.com/show_bug.cgi?id=1935218
Signed-off-by: Or Shoval <oshoval@redhat.com>
```release-note
Add minimal resource requests for macvtap initContainer
```
=> install-cni, Add resources requests for initContainer

version/description, version/version.go
Features:
* install-cni, Add resources requests for initContainer
* dependencies: use containernetworking/plugins v0.9.1
Signed-off-by: Or Shoval <oshoval@redhat.com>
=> Release v0.5.1

README.md
The actual CNI binary is 'macvtap' and not 'macvtap-cni'. Therefore, the configuration sample is not working. The description of the field `type` below is ok, but the configuration sample is missleading.
Fix documentation error
=> Typo in configuration sample

version/description, version/version.go
This new release will allow CNAO to deliver an updated version of multus-cni (v3.8).
The currently released version of [multus](https://github.com/k8snetworkplumbingwg/multus-cni) is v3.8.0, while the version provided by CNAO is v3.4.2.
```release-note
NONE
```
=> Release v0.6.1

automation/check-patch.e2e-k8s.sh, cluster/cluster.sh
This PR bumps kubevirtci to 1.21, which effectively unlocks e2e tests.
```release-note
NONE
```
=> ci: bump kubevirtci to 1.21

README.md
Signed-off-by: xieyanker <xjsisnice@gmail.com>
Fix the NetworkAttachmentDefinition example, I got the error as follows by using it:
```shell
error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: GetCNIConfig: err in getCNIConfigFromSpec: failed to unmarshal Spec.Config: invalid character '"' after object key:value pair
```
```release-note
NONE
```
=> Fix the NetworkAttachmentDefinition example

automation/check-patch.setup.sh
We were still running the unit / func tests using golang 1.13, which has been unsupported since 11 Aug 2020. 
The proposed version - 1.16 - is also unsupported, but we need a follow-up PR to bump both k8s to 1.23 *and* golang to 1.17.
```release-note
NONE
```
=> ci: use golang-1.16

templates/scc.yaml.in
According to [openshift's API specification](https://docs.openshift.com/container-platform/4.10/rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html) the following
attributes are required:
allowHostDirVolumePlugin
allowHostIPC
allowHostNetwork
allowHostPID
allowHostPorts
allowPrivilegedContainer
readOnlyRootFilesystem
This commits adds the required parameters to the SCCs that were missing
them.
This PR is required to unlock [CNAO's PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/1332) .
```release-note
Add the required attributes to comply with the openshift SCC API.
```
=> config, scc: add required parameters

version/description, version/version.go
This PR release macvtap-cni 0.7.0, which features:
* build: bump k8s dependencies to k8s-1.21.11
* config, scc: add required parameters
* Fix the NetworkAttachmentDefinition example
Unlocks CNAO PR https://github.com/kubevirt/cluster-network-addons-operator/pull/1332
```release-note
NONE
```
=> Release v0.7.0

cmd/Dockerfile
Podman doesn't support short name for container image,
use explicit name.
Use quay image to overcome docker rate limits.
```release-note
None
```
=> podman: Use quay full image name

templates/scc.yaml.in
The volume parameter is marked as required in the CRD definition - [0] -
but is not listed as required in the official openshift API - [1].
The tracker bug requesting the API documentation to be updated can be
found in [2].
[0] - https://github.com/openshift/api/blob/a6156965faae5ce117e3cd3735981a3fc0e27e27/security/v1/0000_03_security-openshift_01_scc.crd.yaml#L73
[1] - https://docs.openshift.com/container-platform/4.10/rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html
[2] - https://bugzilla.redhat.com/show_bug.cgi?id=2079224
```release-note
Update the SCC template with a stanza to allow all volume plugins.
```
=> config, scc: add volume parameter

automation/check-patch.setup.sh, manifests/scc.yaml, templates/scc.yaml.in
This PR synchronizes the `macvtap-cni` repo manifests with the defined templates.
It furthermore now adds a check to CI, ensuring these are kept synchronized.
Depends-on: #66 
```release-note
Specify a valid SCC in the manifests.
```
=> Synch repo scc manifest

version/description, version/version.go
Bumps:
- golang to 1.17
- Kubernetes dependencies to 1.23
- corrects the SCC templates for Openshift
```release-note
NONE
```
=> Release v0.8.0

version/description, version/version.go
New release, with bugfixes - most notably, one that allows for macvtap-cni to be deployed in K8s-1.25.
```release-note
NONE
```
=> Release v0.9.0

pkg/deviceplugin/plugin.go
**What this PR does / why we need it**: 
Fix the nil pointer error when deploying to Kubernetes 1.25.  More context can be found [here](https://github.com/kubernetes/kubernetes/pull/109016#issuecomment-1255633896).
To reproduce the issue:
1. Use the minikube to create a cluster with k8s 1.25. `minikube start --kubernetes-version=v1.25`
2. Apply the configmap and the macvtap daemonset.
3.  Check the pod log `kubectl logs -f macvtap-cni-xxxxx`
```release-note
NONE
```
=> Fix nil pointer error for k8s 1.25

tests/e2e/macvtap_test.go
This PR prints the network status annotation when we fail on error
Without knowing the value of the annotation being read it is impossible to understand what is wrong in the test. 
By printing it, we have more information available when bumping dependencies on CI.
Furthermore, we make the test more resilient by defaulting to an empty slice of networks,
and also improve its readability by asserting the annotation is present on the pod.
```release-note
NONE
```
=> e2e tests: print network status annotation on error

tests/e2e/macvtap_test.go
The `networks-status` annotation was deprecated, and replaced by the `network-status` annotation - [0].
[0] - https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/commit/78b3280926a91976a12f710bdd045b41fcfd4073
This PR is required to unlock CNAO's bump to consume multus-v4, since in multus-v4, the old annotation was removed.
```release-note
NONE
```
=> e2e, multi-net: use non-deprecated network-status annot

version/description, version/version.go
Check the network-status annotation from the correct annotation key, rather than an obsolete one.
Multus-v4 no longer features this obsolete annotation, thus this PR unlocks the CNAO bump.
```release-note
NONE
```
=> Release v0.10.1

automation/check-patch.e2e-k8s.sh, cluster/cluster.sh
The 1.23 provider was removed long ago, leaving the project's CI broken. 
This should address it.
```release-note
NONE
```
=> ci, cluster deployment: bump to kubevirtci k8s-1.24

automation/check-patch.e2e-k8s.sh, cluster/cluster.sh
k8s-1.24 is deprecated from latest kubevirtci
```release-note
None
```
=> kubevirtci: Use latest k8s 1.28

automation/check-patch.e2e-k8s.sh, cluster/cluster.sh
Pin tag until `KUBVIRT_WITH_CNAO_SKIP_CONFIG` is
introduced again (it was dropped by mistake).
Beside that:
Allow overriding kubevirtci params.
When running tests from other repos, the cluster that was created
should be the one vendored, so the scripts will match.
Otherwise it can cause errors (for example via CNAO).
Set `KUBEVIRTCI_TAG` and `KUBEVIRT_PROVIDER` only if not set yet.
It also allows overriding locally upon needs.
```release-note
None
```
=> cluster: Pin kubevirtci tag

Makefile, automation/publish.sh, cmd/Dockerfile, hack/build-macvtap-docker.sh, hack/build-macvtap-podman.sh, hack/init-buildx.sh
These changes enable building and pushing macvtap container images for multiple platforms (amd64, s390x, arm64) from a single Dockerfile. Enhanced multi-platform support in the build process by adding a PLATFORMS argument in the Makefile for amd64, s390x, and arm64 architectures. Multi-platform build support is provided for both Docker and Podman container runtimes.
The Macvtap CNI image, available at [[quay.io/kubevirt/macvtap-cni](https://quay.io/repository/kubevirt/macvtap-cni?tab=tags&tag=latest)](https://quay.io/repository/kubevirt/macvtap-cni?tab=tags&tag=latest), currently supports only the amd64 architecture.
This PR introduces the necessary changes for multi-platform container image building and pushes for the macvtap-cni project, including …
=> Add multi-platform support for macvtap cni image builds.

version/description, version/version.go
New patch release
We're skipping v0.12.1 because I have messed up the previous release, and while intending to release v0.12.0 I actually left a leftover in `version/version.go` pointing at v0.12.1 .
```release-note
NONE
```
=> Release v0.12.2

manifests/macvtap.yaml, templates/macvtap.yaml.in
set the TerminationMessagePolicy field to FallbackToLogsOnError [0]
[0]
https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/CATALOG.md#observability-termination-policy
```release-note
NONE
```
=> Set container's TerminationMessagePolicy to FallbackToLogsOnError

manifests/macvtap.yaml
It implementes the readiness and lifeness probes checking the existence of any socket for the macvtap device plugin
```release-note
Add readiness and lifeness probes.
```
=> manifests: Add probes checking device plugin socket
